//! DTOs for the dev-only seed command. The whole module is included only
//! in debug builds via the `#[cfg]`-gated `pub mod seed;` line in
//! `dto/mod.rs`. Frontend bindings are auto-generated by specta when the
//! command is registered (also gated).

use serde::{Deserialize, Serialize};

use crate::application::seed_usecases::{SeedCounts, SeedReport};

/// All counts optional from the frontend; defaults applied in `From`.
#[derive(Debug, Clone, Default, Serialize, Deserialize, specta::Type)]
pub struct SeedCountsDto {
    pub clients: Option<u32>,
    pub catalog_items: Option<u32>,
    pub taxes: Option<u32>,
    pub invoices: Option<u32>,
    pub bookmarks: Option<u32>,
    pub journal_entries_per_client: Option<u32>,
}

impl From<SeedCountsDto> for SeedCounts {
    fn from(dto: SeedCountsDto) -> Self {
        let defaults = SeedCounts::default();
        Self {
            clients: dto.clients.unwrap_or(defaults.clients),
            catalog_items: dto.catalog_items.unwrap_or(defaults.catalog_items),
            taxes: dto.taxes.unwrap_or(defaults.taxes),
            invoices: dto.invoices.unwrap_or(defaults.invoices),
            bookmarks: dto.bookmarks.unwrap_or(defaults.bookmarks),
            journal_entries_per_client: dto
                .journal_entries_per_client
                .unwrap_or(defaults.journal_entries_per_client),
        }
    }
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, specta::Type)]
pub struct SeedReportDto {
    pub clients_added: u32,
    pub catalog_items_added: u32,
    pub taxes_added: u32,
    pub invoices_drafted: u32,
    pub invoices_finalized: u32,
    pub invoices_cancelled: u32,
    pub invoices_sent: u32,
    pub payments_added: u32,
    pub emails_added: u32,
    pub bookmarks_added: u32,
    pub journal_entries_added: u32,
}

impl From<SeedReport> for SeedReportDto {
    fn from(r: SeedReport) -> Self {
        Self {
            clients_added: r.clients_added,
            catalog_items_added: r.catalog_items_added,
            taxes_added: r.taxes_added,
            invoices_drafted: r.invoices_drafted,
            invoices_finalized: r.invoices_finalized,
            invoices_cancelled: r.invoices_cancelled,
            invoices_sent: r.invoices_sent,
            payments_added: r.payments_added,
            emails_added: r.emails_added,
            bookmarks_added: r.bookmarks_added,
            journal_entries_added: r.journal_entries_added,
        }
    }
}
