// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	clientCreate: (input: NewClientDto) => typedError<ClientDto, string>(__TAURI_INVOKE("client_create", { input })),
	clientUpdate: (input: UpdateClientDto) => typedError<ClientDto, string>(__TAURI_INVOKE("client_update", { input })),
	clientArchive: (id: string) => typedError<null, string>(__TAURI_INVOKE("client_archive", { id })),
	clientUnarchive: (id: string) => typedError<null, string>(__TAURI_INVOKE("client_unarchive", { id })),
	clientList: (query: {
	search?: string | null,
	include_inactive?: boolean,
	pagination?: PaginationParamsDto | null,
} | null) => typedError<PageDto<ClientDto>, string>(__TAURI_INVOKE("client_list", { query })),
	clientGet: (id: string) => typedError<ClientDto, string>(__TAURI_INVOKE("client_get", { id })),
	catalogItemCreate: (input: NewCatalogItemDto) => typedError<CatalogItemDto, string>(__TAURI_INVOKE("catalog_item_create", { input })),
	catalogItemUpdate: (input: UpdateCatalogItemDto) => typedError<CatalogItemDto, string>(__TAURI_INVOKE("catalog_item_update", { input })),
	catalogItemArchive: (id: string) => typedError<null, string>(__TAURI_INVOKE("catalog_item_archive", { id })),
	catalogItemUnarchive: (id: string) => typedError<null, string>(__TAURI_INVOKE("catalog_item_unarchive", { id })),
	catalogItemList: (includeInactive: boolean | null) => typedError<CatalogItemDto[], string>(__TAURI_INVOKE("catalog_item_list", { includeInactive })),
	settingsGet: () => typedError<SettingsSnapshotDto, string>(__TAURI_INVOKE("settings_get")),
	/**
	 *  Returns the full list of supported currencies with their display metadata.
	 *  The frontend calls this once at boot to populate its catalog for amount
	 *  formatting and the Settings currency dropdown.
	 */
	settingsSupportedCurrencies: () => typedError<CurrencyConfigDto[], string>(__TAURI_INVOKE("settings_supported_currencies")),
	settingsUpdateSellerProfile: (profile: SellerProfileDto) => typedError<SellerProfileDto, string>(__TAURI_INVOKE("settings_update_seller_profile", { profile })),
	/**
	 *  Updates the app's display currency by ISO 4217 code. The full metadata
	 *  (symbol, fraction digits, unit names) is derived server-side and returned
	 *  in the response so the frontend can keep its cache fresh.
	 */
	settingsUpdateCurrency: (code: string) => typedError<CurrencyConfigDto, string>(__TAURI_INVOKE("settings_update_currency", { code })),
	settingsUpdateAppPreferences: (preferences: AppPreferencesDto) => typedError<AppPreferencesDto, string>(__TAURI_INVOKE("settings_update_app_preferences", { preferences })),
	taxCreate: (input: NewTaxDefinitionDto) => typedError<TaxDefinitionDto, string>(__TAURI_INVOKE("tax_create", { input })),
	taxUpdate: (input: UpdateTaxDto) => typedError<TaxDefinitionDto, string>(__TAURI_INVOKE("tax_update", { input })),
	taxArchive: (id: string) => typedError<null, string>(__TAURI_INVOKE("tax_archive", { id })),
	taxUnarchive: (id: string) => typedError<null, string>(__TAURI_INVOKE("tax_unarchive", { id })),
	taxList: (includeInactive: boolean | null) => typedError<TaxDefinitionDto[], string>(__TAURI_INVOKE("tax_list", { includeInactive })),
	templateCreate: (input: NewInvoiceTemplateDto) => typedError<InvoiceTemplateDto, string>(__TAURI_INVOKE("template_create", { input })),
	templateUpdate: (input: UpdateTemplateDto) => typedError<InvoiceTemplateDto, string>(__TAURI_INVOKE("template_update", { input })),
	templateDelete: (id: string) => typedError<null, string>(__TAURI_INVOKE("template_delete", { id })),
	templateDuplicate: (id: string) => typedError<InvoiceTemplateDto, string>(__TAURI_INVOKE("template_duplicate", { id })),
	templateSetDefault: (id: string) => typedError<null, string>(__TAURI_INVOKE("template_set_default", { id })),
	templateList: () => typedError<InvoiceTemplateDto[], string>(__TAURI_INVOKE("template_list")),
	templatePreview: (input: PreviewTemplateInputDto) => typedError<number[], string>(__TAURI_INVOKE("template_preview", { input })),
	invoiceCreateDraft: (input: NewInvoiceDto) => typedError<InvoiceDto, string>(__TAURI_INVOKE("invoice_create_draft", { input })),
	invoiceUpdateDraft: (input: UpdateDraftInvoiceDto) => typedError<InvoiceDto, string>(__TAURI_INVOKE("invoice_update_draft", { input })),
	invoiceFinalize: (id: string) => typedError<InvoiceDto, string>(__TAURI_INVOKE("invoice_finalize", { id })),
	invoiceDuplicate: (id: string) => typedError<InvoiceDto, string>(__TAURI_INVOKE("invoice_duplicate", { id })),
	invoiceCancel: (id: string) => typedError<InvoiceDto, string>(__TAURI_INVOKE("invoice_cancel", { id })),
	invoiceList: (query: {
	status?: InvoiceStatusDto | null,
	client_id?: string | null,
	search?: string | null,
	pagination?: PaginationParamsDto | null,
} | null) => typedError<PageDto<InvoiceDto>, string>(__TAURI_INVOKE("invoice_list", { query })),
	invoiceGet: (id: string) => typedError<InvoiceDto, string>(__TAURI_INVOKE("invoice_get", { id })),
	settingsUpdateEmailConfig: (config: EmailConfigDto) => typedError<EmailConfigDto, string>(__TAURI_INVOKE("settings_update_email_config", { config })),
	settingsUpdateEmailPassword: (password: string) => typedError<null, string>(__TAURI_INVOKE("settings_update_email_password", { password })),
	emailTestConnection: () => typedError<null, string>(__TAURI_INVOKE("email_test_connection")),
	invoiceSend: (id: string) => typedError<InvoiceDto, string>(__TAURI_INVOKE("invoice_send", { id })),
	emailTemplateCreate: (input: NewEmailTemplateDto) => typedError<EmailTemplateDto, string>(__TAURI_INVOKE("email_template_create", { input })),
	emailTemplateUpdate: (input: UpdateEmailTemplateDto) => typedError<EmailTemplateDto, string>(__TAURI_INVOKE("email_template_update", { input })),
	emailTemplateDelete: (id: string) => typedError<null, string>(__TAURI_INVOKE("email_template_delete", { id })),
	emailTemplateSetDefault: (id: string) => typedError<null, string>(__TAURI_INVOKE("email_template_set_default", { id })),
	emailTemplateList: () => typedError<EmailTemplateDto[], string>(__TAURI_INVOKE("email_template_list")),
	paymentRecord: (input: NewPaymentDto) => typedError<PaymentDto, string>(__TAURI_INVOKE("payment_record", { input })),
	paymentUpdate: (input: UpdatePaymentDto) => typedError<PaymentDto, string>(__TAURI_INVOKE("payment_update", { input })),
	paymentDelete: (id: string) => typedError<null, string>(__TAURI_INVOKE("payment_delete", { id })),
	paymentList: (query: {
	client_id?: string | null,
	search?: string | null,
} | null) => typedError<PaymentDto[], string>(__TAURI_INVOKE("payment_list", { query })),
	paymentGet: (id: string) => typedError<PaymentDto, string>(__TAURI_INVOKE("payment_get", { id })),
	accountingListOutstanding: () => typedError<InvoicePaymentRowDto[], string>(__TAURI_INVOKE("accounting_list_outstanding")),
	accountingListOverdue: () => typedError<InvoicePaymentRowDto[], string>(__TAURI_INVOKE("accounting_list_overdue")),
	accountingRevenueByPeriod: (input: RevenueByPeriodInputDto) => typedError<RevenueBucketDto[], string>(__TAURI_INVOKE("accounting_revenue_by_period", { input })),
	accountingRevenueByClient: (input: RevenueByClientInputDto) => typedError<RevenueByClientDto[], string>(__TAURI_INVOKE("accounting_revenue_by_client", { input })),
	accountingClientBalance: (clientId: string) => typedError<ClientBalanceDto, string>(__TAURI_INVOKE("accounting_client_balance", { clientId })),
	accountingClientBalances: () => typedError<ClientBalanceDto[], string>(__TAURI_INVOKE("accounting_client_balances")),
	accountingAgingReport: () => typedError<AgingRowDto[], string>(__TAURI_INVOKE("accounting_aging_report")),
	accountingDashboardSummary: () => typedError<DashboardSummaryDto, string>(__TAURI_INVOKE("accounting_dashboard_summary")),
	dataExport: (destination: string) => typedError<string, string>(__TAURI_INVOKE("data_export", { destination })),
	dataBackup: (backupDir: string | null) => typedError<string, string>(__TAURI_INVOKE("data_backup", { backupDir })),
	dataRestore: (source: string) => typedError<null, string>(__TAURI_INVOKE("data_restore", { source })),
	dataDefaultBackupDir: () => typedError<string, string>(__TAURI_INVOKE("data_default_backup_dir")),
	notebookSectionCreate: (name: string) => typedError<NotebookSectionDto, string>(__TAURI_INVOKE("notebook_section_create", { name })),
	notebookSectionRename: (input: RenameNotebookSectionDto) => typedError<NotebookSectionDto, string>(__TAURI_INVOKE("notebook_section_rename", { input })),
	notebookSectionDelete: (id: string) => typedError<null, string>(__TAURI_INVOKE("notebook_section_delete", { id })),
	notebookSectionCountEntries: (id: string) => typedError<number, string>(__TAURI_INVOKE("notebook_section_count_entries", { id })),
	notebookSectionReorder: (orderedIds: string[]) => typedError<null, string>(__TAURI_INVOKE("notebook_section_reorder", { orderedIds })),
	notebookSectionList: () => typedError<NotebookSectionDto[], string>(__TAURI_INVOKE("notebook_section_list")),
	clientNotebookGet: (clientId: string) => typedError<ClientNotebookViewDto, string>(__TAURI_INVOKE("client_notebook_get", { clientId })),
	clientNotebookSave: (input: SaveClientNotebookDto) => typedError<null, string>(__TAURI_INVOKE("client_notebook_save", { input })),
	journalEntryCreate: (input: NewJournalEntryDto) => typedError<ClientJournalEntryDto, string>(__TAURI_INVOKE("journal_entry_create", { input })),
	journalEntryUpdate: (input: UpdateJournalEntryDto) => typedError<ClientJournalEntryDto, string>(__TAURI_INVOKE("journal_entry_update", { input })),
	journalEntryDelete: (id: string) => typedError<null, string>(__TAURI_INVOKE("journal_entry_delete", { id })),
	journalListForClient: (clientId: string) => typedError<ClientJournalEntryDto[], string>(__TAURI_INVOKE("journal_list_for_client", { clientId })),
	journalEntryGet: (id: string) => typedError<ClientJournalEntryDto, string>(__TAURI_INVOKE("journal_entry_get", { id })),
};

/* Types */
export type AgingBucketDto = "Current" | "Days1To30" | "Days31To60" | "Days61To90" | "Days91Plus";

export type AgingRowDto = {
	invoice_id: string,
	number: number | null,
	client_id: string,
	client_name: string,
	total: MoneyDto,
	amount_due: MoneyDto,
	due_date: string | null,
	bucket: AgingBucketDto,
};

export type AppPreferencesDto = {
	theme: ThemeDto,
	language: LanguageDto,
	pdf_output_dir: string,
};

export type AppliedTaxDto = {
	tax_definition_id: string | null,
	tax_name: string,
	percentage: string,
	tax_id_number: string | null,
	computed_amount: MoneyDto,
};

export type CatalogItemDto = {
	id: string,
	name: string,
	kind: CatalogItemKindDto,
	default_price: MoneyDto,
	unit: string | null,
	reference: string | null,
	active: boolean,
};

export type CatalogItemKindDto = "Product" | "Service";

export type ClientBalanceDto = {
	client_id: string,
	client_name: string,
	total_invoiced: MoneyDto,
	total_paid: MoneyDto,
	outstanding: MoneyDto,
};

export type ClientDto = {
	id: string,
	name: string,
	emails: ContactEntryDto[],
	phones: ContactEntryDto[],
	address: string | null,
	notes: string | null,
	referred_by: string | null,
	active: boolean,
	created_at: string,
};

export type ClientJournalEntryDto = {
	id: string,
	client_id: string,
	entry_date: string,
	content: string,
	created_at: string,
	updated_at: string,
};

export type ClientNotebookSectionDto = {
	section: NotebookSectionDto,
	content: string,
};

export type ClientNotebookViewDto = {
	client_id: string,
	sections: ClientNotebookSectionDto[],
};

export type ContactEntryDto = {
	id: string | null,
	value: string,
	label: string | null,
	is_default: boolean,
};

/**
 *  Full metadata for a currency as seen by the frontend. The write-side
 *  command only sends `code`; everything else is derived server-side from the
 *  [`Currency`] enum and included on the read path so the UI can render
 *  amounts without a second catalog lookup.
 */
export type CurrencyConfigDto = {
	code: string,
	name: string,
	symbol: string,
	symbol_before: boolean,
	fraction_digits: number,
	main_unit_name: string,
	sub_unit_name: string | null,
};

export type DashboardSummaryDto = {
	revenue_this_year: MoneyDto,
	outstanding_total: MoneyDto,
	overdue_count: number,
	draft_count: number,
	finalized_count: number,
	sent_count: number,
};

export type DerivedPaymentStatusDto = "Draft" | "Unpaid" | "Partial" | "Paid" | "Overdue" | "Cancelled";

export type EmailConfigDto = {
	smtp_host: string,
	smtp_port: number,
	sender_address: string,
};

export type EmailSendDto = {
	id: string,
	template_type: EmailTemplateTypeDto,
	template_name: string,
	to_address: string,
	subject: string,
	sent_at: string,
};

export type EmailTemplateDto = {
	id: string,
	name: string,
	template_type: EmailTemplateTypeDto,
	subject_template: string,
	body_template: string,
	is_default: boolean,
};

export type EmailTemplateTypeDto = "InitialContact" | "FollowUp";

export type FontChoiceDto = "Serif" | "SansSerif" | "Mono";

export type InvoiceDto = {
	id: string,
	number: number | null,
	client_id: string,
	template_id: string | null,
	date: string,
	due_date: string | null,
	line_items: LineItemDto[],
	taxes_applied: AppliedTaxDto[],
	subtotal: MoneyDto,
	tax_total: MoneyDto,
	total: MoneyDto,
	amount_paid: MoneyDto,
	currency: string,
	status: InvoiceStatusDto,
	/**
	 *  Populated by the list/get read paths, where the repo can afford to
	 *  fetch the allocated total alongside the invoice. `None` on write paths
	 *  (create/update/finalize/send/cancel) where callers don't need it.
	 */
	payment_status: DerivedPaymentStatusDto | null,
	pdf_path: string | null,
	notes: string | null,
	email_sends: EmailSendDto[],
	created_at: string,
	updated_at: string,
};

export type InvoicePaymentRowDto = {
	invoice_id: string,
	number: number | null,
	client_id: string,
	client_name: string,
	date: string,
	due_date: string | null,
	total: MoneyDto,
	amount_paid: MoneyDto,
	amount_due: MoneyDto,
	status: InvoiceStatusDto,
	payment_status: DerivedPaymentStatusDto,
};

export type InvoiceStatusDto = "Draft" | "Finalized" | "Sent" | "Cancelled";

export type InvoiceTemplateDto = {
	id: string,
	name: string,
	base_layout: TemplateLayoutDto,
	logo_image: number[] | null,
	accent_color: string | null,
	font_family: FontChoiceDto,
	show_seller_phone: boolean,
	show_seller_email: boolean,
	show_registration_id: boolean,
	show_tax_id_numbers: boolean,
	show_signature: boolean,
	show_due_date: boolean,
	show_total_in_words: boolean,
	header_text: string | null,
	footer_text: string | null,
	is_default: boolean,
};

export type LanguageDto = "Fr" | "En";

export type LineItemDto = {
	id: string,
	description: string,
	quantity: string,
	unit_price: MoneyDto,
	total: MoneyDto,
};

export type ListClientsQueryDto = {
	search?: string | null,
	include_inactive?: boolean,
	pagination?: PaginationParamsDto | null,
};

export type ListInvoicesQueryDto = {
	status?: InvoiceStatusDto | null,
	client_id?: string | null,
	search?: string | null,
	pagination?: PaginationParamsDto | null,
};

export type ListPaymentsQueryDto = {
	client_id?: string | null,
	search?: string | null,
};

/**
 *  Wire format for a monetary amount. `amount_minor` is the integer count of
 *  the currency's smallest unit (cents for EUR, yen for JPY, etc.) — see the
 *  doc on [`crate::domain::money::Money`] for the full contract.
 */
export type MoneyDto = {
	amount_minor: number,
	currency: string,
};

export type NewCatalogItemDto = {
	name: string,
	kind: CatalogItemKindDto,
	default_price: MoneyDto,
	unit: string | null,
	reference: string | null,
};

export type NewClientDto = {
	name: string,
	emails: ContactEntryDto[],
	phones: ContactEntryDto[],
	address: string | null,
	notes: string | null,
	referred_by: string | null,
};

export type NewEmailTemplateDto = {
	name: string,
	template_type: EmailTemplateTypeDto,
	subject_template: string,
	body_template: string,
};

export type NewInvoiceDto = {
	client_id: string,
	template_id: string | null,
	date: string,
	due_date: string | null,
	line_items: NewLineItemDto[],
	tax_ids: string[],
	notes: string | null,
	currency: string,
};

export type NewInvoiceTemplateDto = {
	name: string,
	base_layout: TemplateLayoutDto,
	logo_image: number[] | null,
	accent_color: string | null,
	font_family: FontChoiceDto,
	show_seller_phone: boolean,
	show_seller_email: boolean,
	show_registration_id: boolean,
	show_tax_id_numbers: boolean,
	show_signature: boolean,
	show_due_date: boolean,
	show_total_in_words: boolean,
	header_text: string | null,
	footer_text: string | null,
};

export type NewJournalEntryDto = {
	client_id: string,
	entry_date: string,
	content: string,
};

export type NewLineItemDto = {
	description: string,
	quantity: string,
	unit_price: MoneyDto,
};

export type NewPaymentAllocationDto = {
	invoice_id: string,
	amount: MoneyDto,
};

export type NewPaymentDto = {
	client_id: string,
	date: string,
	amount: MoneyDto,
	method: PaymentMethodDto,
	reference: string | null,
	allocations: NewPaymentAllocationDto[],
	notes: string | null,
};

export type NewTaxDefinitionDto = {
	name: string,
	percentage: string,
	tax_id_number: string | null,
};

export type NotebookEntryDto = {
	section_id: string,
	content: string,
};

export type NotebookSectionDto = {
	id: string,
	name: string,
	sort_order: number,
};

// Serializable mirror of [`crate::application::ports::Page`] for the IPC boundary.
export type PageDto<T> = {
	first: number,
	last: number,
	previous: number | null,
	next: number | null,
	total: number,
	data: T[],
};

// Pagination input parameters sent from the frontend.
export type PaginationParamsDto = {
	page?: number | null,
	per_page?: number | null,
};

export type PaymentAllocationDto = {
	invoice_id: string,
	amount: MoneyDto,
};

export type PaymentDto = {
	id: string,
	client_id: string,
	date: string,
	amount: MoneyDto,
	method: PaymentMethodDto,
	reference: string | null,
	allocations: PaymentAllocationDto[],
	notes: string | null,
	created_at: string,
};

export type PaymentMethodDto = { kind: "BankTransfer" } | { kind: "Cash" } | { kind: "Check" } | { kind: "Card" } | { kind: "Other"; detail: string };

export type PreviewTemplateInputDto = {
	template_id?: string | null,
	overrides?: TemplateOverrideDto | null,
};

export type RenameNotebookSectionDto = {
	id: string,
	name: string,
};

export type RevenueBucketDto = {
	bucket_start: string,
	amount: MoneyDto,
	invoice_count: number,
};

export type RevenueByClientDto = {
	client_id: string,
	client_name: string,
	total_invoiced: MoneyDto,
	invoice_count: number,
};

export type RevenueByClientInputDto = {
	start: string,
	end: string,
};

export type RevenueByPeriodInputDto = {
	start: string,
	end: string,
	grouping: RevenueGroupingDto,
};

export type RevenueGroupingDto = "Day" | "Month" | "Year";

export type SaveClientNotebookDto = {
	client_id: string,
	entries: NotebookEntryDto[],
};

export type SellerProfileDto = {
	name: string,
	title: string | null,
	registration_id: string | null,
	address: string | null,
	phone: string | null,
	email: string | null,
	signature_image: number[] | null,
};

export type SettingsSnapshotDto = {
	seller: SellerProfileDto,
	currency: CurrencyConfigDto,
	preferences: AppPreferencesDto,
	email: EmailConfigDto,
	has_email_password: boolean,
};

export type TaxDefinitionDto = {
	id: string,
	name: string,
	percentage: string,
	tax_id_number: string | null,
	active: boolean,
};

export type TemplateLayoutDto = "Classic" | "Modern" | "Minimal";

export type TemplateOverrideDto = {
	base_layout: TemplateLayoutDto,
	accent_color: string | null,
	font_family: FontChoiceDto,
	logo_image: number[] | null,
	show_seller_phone: boolean,
	show_seller_email: boolean,
	show_registration_id: boolean,
	show_tax_id_numbers: boolean,
	show_signature: boolean,
	show_due_date: boolean,
	show_total_in_words: boolean,
	header_text: string | null,
	footer_text: string | null,
};

export type ThemeDto = "Light" | "Dark";

export type UpdateCatalogItemDto = {
	id: string,
	name: string,
	kind: CatalogItemKindDto,
	default_price: MoneyDto,
	unit: string | null,
	reference: string | null,
};

export type UpdateClientDto = {
	id: string,
	name: string,
	emails: ContactEntryDto[],
	phones: ContactEntryDto[],
	address: string | null,
	notes: string | null,
	referred_by: string | null,
};

export type UpdateDraftInvoiceDto = {
	id: string,
	template_id: string | null,
	date: string,
	due_date: string | null,
	line_items: NewLineItemDto[],
	tax_ids: string[],
	notes: string | null,
};

export type UpdateEmailTemplateDto = {
	id: string,
	name: string,
	subject_template: string,
	body_template: string,
};

export type UpdateJournalEntryDto = {
	id: string,
	entry_date: string,
	content: string,
};

export type UpdatePaymentDto = {
	id: string,
	date: string,
	amount: MoneyDto,
	method: PaymentMethodDto,
	reference: string | null,
	allocations: NewPaymentAllocationDto[],
	notes: string | null,
};

export type UpdateTaxDto = {
	id: string,
	name: string,
	percentage: string,
	tax_id_number: string | null,
};

export type UpdateTemplateDto = {
	id: string,
	name: string,
	base_layout: TemplateLayoutDto,
	logo_image: number[] | null,
	accent_color: string | null,
	font_family: FontChoiceDto,
	show_seller_phone: boolean,
	show_seller_email: boolean,
	show_registration_id: boolean,
	show_tax_id_numbers: boolean,
	show_signature: boolean,
	show_due_date: boolean,
	show_total_in_words: boolean,
	header_text: string | null,
	footer_text: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

